const callList = [
    {
      id: 1,
      firstName: "Min",
      lastName: "Kevin",
      addressLine: "25 Arundel St",
      city: "Glebe",
      state: "NSW",
      postCode: "2037",
      phone: "0405000000",
      visitType: "Silent",
      status: "Active",
      transcription: "I need a seafood pizza. I need a seafood pizza. I need a seafood pizza."
    },
    {
      id: 2,
      firstName: "John",
      lastName: "Smith",
      addressLine: "123 Main St",
      city: "Anytown",
      state: "CA",
      postCode: "12345",
      phone: "0405000000",
      visitType: "Regular",
      status: "Missed",
      transcription: "Please schedule a pizza delivery. Please schedule a pizza delivery."
    },
    {
      id: 3,
      firstName: "Emma",
      lastName: "Johnson",
      addressLine: "789 Elm St",
      city: "Anothercity",
      state: "NY",
      postCode: "54321",
      phone: "0405000000",
      visitType: "Urgent",
      status: "Pending",
      transcription: "I need immediate pizza assistance. I need immediate pizza assistance."
    },
    {
      id: 4,
      firstName: "Alex",
      lastName: "Brown",
      addressLine: "456 Oak St",
      city: "Sometown",
      state: "TX",
      postCode: "98765",
      phone: "0405000000",
      visitType: "Regular",
      status: "Active",
      transcription: "Can I schedule a pizza delivery for next week? Can I schedule a pizza delivery for next week?"
    },
    {
      id: 5,
      firstName: "Sarah",
      lastName: "Davis",
      addressLine: "789 Maple Ave",
      city: "Townville",
      state: "FL",
      postCode: "54321",
      phone: "0405000000",
      visitType: "Silent",
      status: "Missed",
      transcription: "I have a question about my pizza order. I have a question about my pizza order."
    },
    {
      id: 6,
      firstName: "Michael",
      lastName: "Lee",
      addressLine: "987 Pine Rd",
      city: "Cityville",
      state: "CA",
      postCode: "12345",
      phone: "0405000000",
      visitType: "Urgent",
      status: "Pending",
      transcription: "I need immediate pizza medical attention. I need immediate pizza medical attention."
    },
    // Additional data
    {
      id: 7,
      firstName: "Emily",
      lastName: "Wilson",
      addressLine: "567 Elm St",
      city: "Townsville",
      state: "FL",
      postCode: "54321",
      phone: "0407000000",
      visitType: "Regular",
      status: "Active",
      transcription: "I have a question about my pizza delivery. I have a question about my pizza delivery."
    },
    {
      id: 8,
      firstName: "Daniel",
      lastName: "Thomas",
      addressLine: "789 Oak St",
      city: "Anycity",
      state: "CA",
      postCode: "12345",
      phone: "0408000000",
      visitType: "Silent",
      status: "Missed",
      transcription: "I need to reschedule my pizza delivery. I need to reschedule my pizza delivery."
    },
    {
      id: 9,
      firstName: "Olivia",
      lastName: "Anderson",
      addressLine: "987 Maple Ave",
      city: "Sometown",
      state: "TX",
      postCode: "98765",
      phone: "0409000000",
      visitType: "Urgent",
      status: "Missed",
      transcription: "I have a question about my pizza order. I have a question about my pizza order."
    },
    {
      id: 10,
      firstName: "William",
      lastName: "Taylor",
      addressLine: "456 Pine Rd",
      city: "Cityville",
      state: "CA",
      postCode: "12345",
      phone: "0410000000",
      visitType: "Regular",
      status: "Missed",
      transcription: "Can I schedule a pizza delivery for next week? Can I schedule a pizza delivery for next week?"
    },
    {
      id: 11,
      firstName: "Sophia",
      lastName: "Walker",
      addressLine: "789 Elm St",
      city: "Townsville",
      state: "FL",
      postCode: "54321",
      phone: "0411000000",
      visitType: "Silent",
      status: "Pending",
      transcription: "I have a question about my pizza order. I have a question about my pizza order."
    },
    {
      id: 12,
      firstName: "James",
      lastName: "Harris",
      addressLine: "987 Pine Rd",
      city: "Cityville",
      state: "CA",
      postCode: "12345",
      phone: "0412000000",
      visitType: "Urgent",
      status: "Pending",
      transcription: "I need immediate pizza medical attention. I need immediate pizza medical attention."
    }
  ];
  
  export default callList;
  